growth_accounting:
  outputs:
    dev:
      type: postgres
      threads: 8
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PGPORT') | int }}"
      user: "{{ env_var('PGUSER') }}"
      pass: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      schema: public
  target: dev
